games:
    controllers:
        -
            controller: GameListController
            route: games:list
            url: /
        -
            controller: GameActiveListController
            route: games:active_list
            url: /active
        -
            controller: GroupAController
            route: games:group_a
            url: /group_a
        -
            controller: GroupBController
            route: games:group_b
            url: /group_b
        -
            controller: FinalsController
            route: games:finals
            url: /finals
    admin:
        -
            controller: AdminGameListController
            route: games:admin_list
            url: /admin
        -
            controller: GameEditController
            route: games:admin
            url: /admin/{obj_id:\d+}
        -
            controller: GameEditScoreController
            route: games:admin_score
            url: /admin/score/{obj_id:\d+}
        -
            controller: AdminGameListScoreController
            route: games:admin_score_list
            url: /admin/games/scores
